### ISSUE TITLE
Custom modal Biometric does not work

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#1]
On the "Create New Mnemonic" flux, the custom modal for the biometric verification does not work (you can't cancel). 
As from the discussion on the discord channel, we can proceed in removing this modal and using the default system. This should be the default behavior anywhere the biometric verification is needed.

Implementation:
![image](https://user-images.githubusercontent.com/13519292/171004481-80f7e58d-bf31-4fbc-8eb2-407d265a93a8.png)

**Comment by zheleznov163** [comment]
Need clarification, what behavior is expected on devices that do not support a biometric scanner?

**Comment by giorgionocera** [comment]
The flux will change a bit. Up to now, only consider that if biometric scanning is needed, use the default system.

**Comment by giorgionocera** [comment]
Thank you!
