### ISSUE TITLE
Add Biometric Authentication Flow

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#12]
We should evaluate and add the UI flow for the biometric authentication. I suggest to add it after the PIN creation, like it's done on bank's applications.
In addition, it could be useful to consider that the user is not required to use the biometric. It can be only used to avoid inserting every time the PIN code.
For this reason, if the user don't want to use it, he can move forward and insert the PIN code every time it's needed.

**Comment by gabriele-pala** [comment]
@DavideSegullo 
Is on Figma in “0.6" with explanations.
