### ISSUE TITLE
App lock timer

### ISSUE THREAD

**Issue by EnricoBarbieri1997** [bitsongofficial/wallet-mobile#126]
Right now app timer updates itself each second decreasing the remaining time.
We should move to an implementation where it takes as input the block end time and shows the remaining time. The reason is that is both more efficient and enables to store the end time locally so the user can't just close the app and reopen it to elude the block.

**Comment by zheleznov163** [comment]
I changed the timer behavior significantly, and initialized it as an example in the SettignsStore.
It probably needs some extra code to check for a lock during application startup. I added a save to storage but didn't test it and left it commented out
