### ISSUE TITLE
Add Loading State

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#15]
We must add loading state UI, each time a user perform some action on the chain (it could take some seconds) we should give a feedback to the user.

Maybe we can create different types of loaders for example:
1) Inline loader (inside a button for example)
2) Full screen loader, for blocking actions
3) Bar loader

I also suggest to add some example and prototype inside Figma, a good use case could be when a user sign a transaction (for example a send action).

**Comment by gabriele-pala** [comment]
@DavideSegullo 
Send Transaction Pending, Send Transaction Successful & Send Transaction Error on Figma "Cosmonautico 0.6"

**Comment by DavideSegullo** [comment]
Thank you @gabriele-pala, we can move it to development @zheleznov163
