### ISSUE TITLE
Hide Phrase button

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#2]
On the "Create New Mnemonic" flux, the button to **show/hide** the seed phrase is not working correctly.
As it is possible to see from the images below, the button is not changing to "Hide Phrase".

Implementation:
![hide-phrase-btn](https://user-images.githubusercontent.com/13519292/171008272-dff4f919-5fcb-48a3-b70e-a756552c4b38.jpg)

Design:
![hide-phrase-btn-design](https://user-images.githubusercontent.com/13519292/171008821-29fcd7a2-c9c2-4445-8a8f-54e63b31c261.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
