### ISSUE TITLE
Add Backdrop Behind Bottom Sheet

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#21]
We should add a backdrop element behind every bottom sheet we are using, for example:
1) All actions
2) Send
3) Import wallet 
4) Ecc.

That is required because we'll also add a **_close to dismiss_** action on the backdrop element

**Comment by gabriele-pala** [comment]
@DavideSegullo
fixed

**Comment by gabriele-pala** [comment]
@DavideSegullo 
The backdrop is #14142E with opacity 0.75

**Comment by DavideSegullo** [comment]
Thank you @gabriele-pala, we can move it to development @zheleznov163 , you can find the design on Figma (Version 0.6)

**Comment by giorgionocera** [comment]
@zheleznov163 I do not see the backdrop behind the send bottom sheet at the moment in the dev branch.
Can you give me feedback?

**Comment by giorgionocera** [comment]
It is also missing on the other bottom sheets
