### ISSUE TITLE
Improve Currency & Language Bottom Sheet

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#22]
We can improve the bottom sheet experience by removing the button **_Seleziona ${value}_**, so if the user change the value of a radio button we can automatically save it.

![Lingua - 375px (1)](https://user-images.githubusercontent.com/17269969/173522071-aa610480-fbe1-455b-b7f3-c920c5ab911e.png)

**Comment by giorgionocera** [comment]
Opening the language bottom sheet many times results in breaking the bottom sheet. Sometimes it'll be not opened, some others time it is slowly opened.
