### ISSUE TITLE
Continue button arrow missing

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#3]
On all the continue buttons, the arrow symbol is missing. 
We talked about that on the Discord channel, so you can find more info (also your response @zheleznov163) on that channel.

Implementation:
![continue-btn](https://user-images.githubusercontent.com/13519292/171010371-60938663-8fd3-4cbc-a6ce-440db14a4865.jpg)

Design:
![continue-btn-design](https://user-images.githubusercontent.com/13519292/171010460-75529185-991e-474a-8ea9-449c9e6003ac.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
