### ISSUE TITLE
Fix Dark Mode Rendering

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#36]
On Android devices, there are some issues with dark mode, as you can see on the screenshots below:

1. Wrong icon color
2. Pin dots are transparent
3. Stepper dots color is wrong
4. Dashboard buttons
5. Profile page
6. ecc

I'm using a Xiaomi Mi 9T Pro with Android 11.

![photo5859533997313472838](https://user-images.githubusercontent.com/17269969/173786851-d9846c3a-d9f2-45b8-945e-fb1ff2fd0994.jpg)
![photo5859533997313472847](https://user-images.githubusercontent.com/17269969/173790975-16bded7d-8421-43a1-9d80-9fb16b281427.jpg)
![photo5859533997313472845](https://user-images.githubusercontent.com/17269969/173790983-bbb3ea05-67fe-4159-958e-862297f7b8f5.jpg)
![photo5859533997313472844](https://user-images.githubusercontent.com/17269969/173790995-c7c6c986-e548-4a6a-9b2d-4f4d110bce2b.jpg)
![photo5859533997313472846](https://user-images.githubusercontent.com/17269969/173791004-176933dc-bac6-41e3-99a8-007fbe0d994a.jpg)

**Comment by zheleznov163** [comment]
Needed to test on device.

**Comment by DavideSegullo** [comment]
Thanks @zheleznov163 It works!
