### ISSUE TITLE
Different spacings in create new mnemonic

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#4]
On the "Create New Mnemonic" flux, the spacings between the header and the first title seem to be different.
Maybe you can give a look at the following image for better clarification.

Implementation:
![spacings](https://user-images.githubusercontent.com/13519292/171011960-72978fee-8cbe-4445-ad42-6bbef6202bbd.jpg)

Design:
![spacings-design](https://user-images.githubusercontent.com/13519292/171012234-d888aa6d-2e82-479a-a53f-e40a13b4bcb1.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
