### ISSUE TITLE
Back button too down

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#5]
On the "Create New Mnemonic" flux, when the user needs to add the wallet name, once the user opens the keyboard, the "Back" button appears too down. It is cut by part of the keyboard.

Implementation
![back-button](https://user-images.githubusercontent.com/13519292/171012612-869f7bdc-3f4b-4d25-9bed-9eb238c2eb62.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
