### ISSUE TITLE
Remove unnecessary elements on header

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#55]
In the confirm pin interface or in the operation confirmed screen (as examples) the header also contains unnecessary elements.
We need to remove them where they are not needed.
![photo_2022-07-05 10 03 07](https://user-images.githubusercontent.com/13519292/177280124-41e3681c-56b9-484f-b1be-502bc8dc02b5.jpeg)
![photo_2022-07-05 10 03 09](https://user-images.githubusercontent.com/13519292/177280133-4f48924c-2793-4af0-a07d-fa8d0ae1f3ff.jpeg)

**Comment by gabriele-pala** [comment]
Hello Giorgio, 

1. In the "operation confirmed" screen, remove menu header and we will put the logo at the center, like this:
![Operation Confirmed - 375px](https://user-images.githubusercontent.com/105061015/177281317-915aa72f-e8df-44bf-b5b3-d8ece6c4eef3.png)

2. Remove the stepper at the top left in the "set pin" & "confirm pin".

3. "cosmonautico" at the top, in the current design is not at the center. 
![Screenshot_2022-07-05-10-31-11-436_com bitsong wallet](https://user-images.githubusercontent.com/105061015/177285713-3e953901-2515-4c36-91d7-d59d546be102.jpg)


This is the correct design:
<img width="1164" alt="Schermata 2022-07-05 alle 10 29 20" src="https://user-images.githubusercontent.com/105061015/177285385-0fa498f4-b4cb-4823-b65f-9bd2d792f4aa.png">
