### ISSUE TITLE
Less than 4 letter name for the wallet

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#6]
On the "Create New Mnemonic" flux, when the user needs to add a name for its new wallet, if the name contains less than 4 letters, the "continue" button is not present. It appears only when the name contains at least 4 letters.
This behavior should be improved by continuing always show the button and only changing its status from disabled (when less than 4 letters are used) to enabled (once at least 4 letters are used).

Implementation:
![less-than-4-char](https://user-images.githubusercontent.com/13519292/171013708-685804b2-8580-4d89-9ccc-476ee66539f5.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
