### ISSUE TITLE
Transaction recap 

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#62]
In the transaction recap screen (sign a transaction from a web app), they are missing:
- title,
- details
- data
- "add to contact" button is replaced by an empty button

![photo_2022-07-05 10 37 07](https://user-images.githubusercontent.com/13519292/177286743-7fdbb9f7-9398-4df7-9aba-19e87cc090f7.jpeg)

![photo_2022-07-05 10 38 31](https://user-images.githubusercontent.com/13519292/177287043-1374a779-bce0-459e-bd17-1cd09caa724d.jpeg)

**Comment by DavideSegullo** [comment]
@EnricoBarbieri1997  As you can see there are two issues:

1. If I wanna transfer 1 dollar, there is a round up error
2. There is an error related to the decimals, i think less decimals are ok

![photo_6005926531668490505_y](https://user-images.githubusercontent.com/17269969/182864398-87f1ecae-31b3-4573-bc82-a421d5ff854a.jpg)
![photo_6005926531668490504_y](https://user-images.githubusercontent.com/17269969/182864407-2dd34855-3cbd-4c05-ba67-9503b1dc501a.jpg)

**Comment by giorgionocera** [comment]
In order to maintain a "nice to see" behavior for the numbers, we need to choose a standard to show the number of digit.
We have to show:
- 4 decimal digits (after the point) up to when the number has 5 integer digits (ex. 12345.1111);
- 2 decimal digits (after the point) up to when the number has 6 or 7 integer digits (ex. 1234567.11);
- remove the decimals otherwise.

So to recap, we can show up to 4 decimals for numbers up to 99999.9999.
From 100000.00 to 9999999.99, we can show 2 decimals and, from 10000000, we do not show decimals.

If the number is 1 billion or larger, we can use 1B and so on starting from this number.
