### ISSUE TITLE
Custom keyboard security improvement

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#7]
On the "Create New Mnemonic" flux, when the custom keyboard is shown for the pin selection, it is static.
Generally, when a custom keyboard is used to add a secret PIN, its purpose is to be "harder to steal". In such a context, as it is possible to see from the different implementations of custom keyboards used for PINs, they contain the number in random order. It increase the security in different scenarios.
For this reason, it could be better, if the custom component PIN keyboard, could contain the number in random order on each shown.

Implementation:
![random-position](https://user-images.githubusercontent.com/13519292/171019917-bd94ec8f-7e0b-4fc6-bdb6-be6f6f30fb9f.jpg)

**Comment by DavideSegullo** [comment]
Fixed on branch [NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo](https://github.com/bitsongofficial/wallet-mobile/tree/NikitaZheleznov/0.0.0-fix_bugs_fist_internal_demo)
