### ISSUE TITLE
Disable Screenshot ability

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/wallet-mobile#74]
As per a home banking application, since there is a lot of sensible data, we need to disable the ability to take screenshots on the mobile app.

**Comment by EnricoBarbieri1997** [comment]
It's not possible to prevent screenshot on iOS in a conventional way. Added this feature on Android 733ba7e0cc6cb19d661bc08dca0d611030935006

**Comment by giorgionocera** [comment]
Okay, thank you for this information. I agree with you that, since iOS avoid this practice with an official flow, it should be better to avoid using a workaround to implement it.
