### ISSUE TITLE
UI Fix - Select a Wallet

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#98]
We have a problem related to the absolute position of "Select" button, in my cell phone is cut off

Current implementation:
![photo_6005926531668490426_y](https://user-images.githubusercontent.com/17269969/182813519-ac679d86-7758-48a3-be1f-c173b349fc34.jpg)

Design implementation:
![image](https://user-images.githubusercontent.com/17269969/182813739-66033381-6521-4908-b339-41d8776e14c1.png)

**Comment by zheleznov163** [comment]
There is no problem in the current version. Changed how bottomsheet's footer is rendered during refactoring

**Comment by EnricoBarbieri1997** [comment]
Button position is now correct but the list needs to scroll
![image](https://user-images.githubusercontent.com/12893767/188527875-a1e302d8-3100-42c5-9944-67da3b9bb3fc.png)

**Comment by zheleznov163** [comment]
> Button position is now correct but the list needs to scroll 

fixed
